### ISSUE TITLE
`X-Forwarded-Prefix` not set

### ISSUE THREAD

**Issue by rsemlal** [alexashley/kong-plugin-path-prefix#10]
When this plugin is used to strip a path prefix from the url, the header `X-Forwarded-Prefix` is not set to let the upstream service know how it is accessed.

## Why is this a problem

The availability of this header is needed in particular when the upstream service is using [HAL](https://datatracker.ietf.org/doc/html/draft-kelly-json-hal-08) or something similar where the Rest API should include in the response links to other resources, so they need to be aware of their external url when accessed behind Kong.

## How to reproduce

A simple example, using Kong Ingress Controller and this plugin:

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: strip-demo-2-path-prefix
config:
  path_prefix: "/foo/"
plugin: path-prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-2
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/plugins: strip-demo-2-path-prefix
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - backend:
          service:
            name: echo
            port:
              number: 80
        path: /foo/bar
        pathType: ImplementationSpecific
```

### Expected result

The request routed to the upstream service should have the header `X-Forwarded-Prefix: /foo`

### Found result

The request routed to the upstream service has no `X-Forwarded-Prefix` header.

### Further investigations

If Kong strip path feature is enabeled (using `konghq.com/strip-path: "true"` in the ingress resource), the header `X-Forwarded-Prefix: /foo/bar` is added, which is not correct either.

### Workaround

A workaround is to use Kong `post-function` plugin to manually set the header (see. https://github.com/Kong/kong/issues/5559).

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: strip-demo-2-path-prefix
config:
  path_prefix: "/foo/"
plugin: path-prefix
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: set-forwarded-header
plugin: post-function
config:
  access:
    - |
      ngx.var.upstream_x_forwarded_prefix='/foo'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-2
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/plugins: strip-demo-2-path-prefix,set-forwarded-header
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - backend:
          service:
            name: echo
            port:
              number: 80
        path: /foo/bar
        pathType: ImplementationSpecific
```

## Suggested solution

Either to make the plugin set the header based on the value of `path_prefix` or (maybe better) add a new (optional) configuration field that allows setting custom values for the header
